const AMBASSADOR_MISSION = [
  "Invite talented Citizens to join Paragon Planet",
  "Discover and promote Stars across different talent categories",
  "Build and grow your own network of Citizens",
  "Support the visibility, branding, and development of your invited Stars",
  "Help talents gain recognition, votes, followers, and opportunities",
  "Promote engagement and participation within the ecosystem",
  "Earn rewards from the success and activities of your Citizens",
];

export default function AmbassadorAboutContent({ footer = null, theme = "light" }) {
  const dark = theme === "dark";
  const textStyle = dark ? darkTextStyle : lightTextStyle;
  const listStyle = dark ? darkListStyle : lightListStyle;
  const highlightStyle = dark ? darkHighlightStyle : lightHighlightStyle;

  return (
    <div>
      <h2 style={titleStyle}>About Ambassadors</h2>
      <p style={textStyle}>
        Paragon Planet Ambassadors are promotional Stars, talent scouts, artist managers, MCs,
        presenters, media personalities, entertainment promoters, influencers, and talent
        representatives who discover, invite, support, and promote talented Stars into the Paragon
        Planet ecosystem through their unique invitation links.
      </p>
      <p style={textStyle}>
        Ambassadors serve as important promotional forces within the Planet by helping talented
        individuals gain visibility, audience engagement, recognition, and opportunities within the
        ecosystem.
      </p>

      <h3 style={subtitleStyle}>As an Ambassador, Your Mission Is To:</h3>
      <ul style={listStyle}>
        {AMBASSADOR_MISSION.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>

      <p style={highlightStyle}>
        When a Citizen joins through an Ambassador's invitation link, the Ambassador becomes
        connected to that Citizen within the platform's promotional structure. Based on the
        platform's reward system, Ambassadors earn commission rewards from the votes and engagement
        activities generated by their invited Citizens.
      </p>
      <p style={textStyle}>
        Ambassadors play a major role in expanding the Planet by connecting hidden talents to
        contests, promotions, audience visibility, sponsorship opportunities, entertainment
        exposure, and recognition within the Paragon Planet ecosystem.
      </p>
      <p style={textStyle}>
        Outstanding Ambassadors who successfully build, manage, and promote high-performing
        Citizens across multiple categories may qualify for higher Planet Levels, special
        recognition statuses, exclusive rewards, and leadership opportunities within the Game of
        ALL STARS GBAZILO.
      </p>
      {footer}
    </div>
  );
}

const titleStyle = {
  marginTop: 0,
};

const subtitleStyle = {
  marginBottom: 8,
};

const lightTextStyle = {
  margin: "0 0 12px",
  lineHeight: 1.65,
  color: "#26384d",
};

const darkTextStyle = {
  margin: "0 0 12px",
  lineHeight: 1.65,
  color: "#d9d4ca",
};

const lightListStyle = {
  margin: "0 0 14px",
  paddingLeft: 22,
  lineHeight: 1.7,
  color: "#26384d",
};

const darkListStyle = {
  margin: "0 0 14px",
  paddingLeft: 22,
  lineHeight: 1.7,
  color: "#f3efe6",
};

const lightHighlightStyle = {
  margin: "0 0 12px",
  padding: 14,
  borderRadius: 10,
  background: "#101828",
  color: "#fff",
  fontWeight: 800,
  lineHeight: 1.55,
};

const darkHighlightStyle = {
  margin: "0 0 12px",
  padding: 14,
  borderRadius: 10,
  background: "#f3efe6",
  color: "#101828",
  fontWeight: 800,
  lineHeight: 1.55,
};
