package com.app.natureswayproduction.nativeapp.navigation

sealed class AppDestination(val route: String) {
    data object Feed : AppDestination("feed")
    data object Watch : AppDestination("watch")
    data object Upload : AppDestination("upload")
    data object Wallet : AppDestination("wallet")
    data object Profile : AppDestination("profile")
    data object Admin : AppDestination("admin")
    data object Auth : AppDestination("auth")
    data object Roles : AppDestination("roles")
    data object EarnRoles : AppDestination("earn_roles")
    data object CitizenOnboarding : AppDestination("onboarding_citizen")
    data object PromoterOnboarding : AppDestination("onboarding_promoter")
    data object MerchantOnboarding : AppDestination("onboarding_merchant")
    data object MerchantMarketplace : AppDestination("merchant_marketplace")
    data object MerchantAbout : AppDestination("merchant_about")
    data object CitizenContestants : AppDestination("citizen_contestants")
    data object SuperbossDirectory : AppDestination("superboss_directory")
    data object BackerDirectory : AppDestination("backer_directory")
    data object AmbassadorDirectory : AppDestination("ambassador_directory")
    data object SponsorInvestorAbout : AppDestination("sponsor_investor_about")
    data object AboutPlanet : AppDestination("about_planet")
    data object PrivacyPolicy : AppDestination("privacy_policy")
    data object BackerOnboarding : AppDestination("onboarding_backer")
    data object SupernalOnboarding : AppDestination("onboarding_supernal")
    data object SponsorInvestorOnboarding : AppDestination("onboarding_sponsor_investor")
    data object UserOnboarding : AppDestination("onboarding_user")
    data object UserAbout : AppDestination("user_about")
    data object MeetUp : AppDestination("meet_up")
}
